MOUSEKEY_ENABLE			= no    # Mouse keys
VIA_ENABLE			 	= no    # Enable VIA
LTO_ENABLE				= yes
OLED_ENABLE				= yes
RGBLIGHT_ENABLE			= no
RGB_MATRIX_ENABLE	 	= yes
EXTRAKEY_ENABLE			= yes
CONSOLE_ENABLE		    = no         # Console for debug
COMMAND_ENABLE			= no
TAP_DANCE_ENABLE		= yes
SPLIT_KEYBOARD			= yes
#RGB_MATRIX_CUSTOM_USER  = yes
